[Reply] Added dynamic colors and styled bars
material-components/material-components-android-examples pull request #78
Opened 2021-09-29 20:36 UTC by DavidHewWing

- Added Dynamic Colors
- Transparent StatusBar and Transparent NavBar

2021-09-29 20:41 UTC, DavidHewWing commented
Moving changes over to https://github.com/material-components/material-components-android-examples/pull/78.

2021-09-30 13:42 UTC, hunterstich requested changes

2021-09-30 13:42 UTC, hunterstich commented on Reply/app/src/main/res/values/themes.xml
> +	      <item name="android:statusBarColor">@android:color/transparent</item>
Fix indentation.

Also, let's put these android specific attrs after the color slot assignments - after `scrimBackground` where they where.

2021-09-30 15:30 UTC, hunterstich approved these changes

2021-09-30 15:58 UTC, merged